import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { users, listings } from "@/lib/schema";
import bcrypt from "bcryptjs";

export async function GET() {
  await db.delete(listings);
  await db.delete(users);

  const hashedPassword = await bcrypt.hash("demo123", 10);

  const [seller] = await db.insert(users).values({
    name: "Demo Seller",
    email: "seller@demo.com",
    password: hashedPassword,
    phone: "+998901234567",
    role: "seller",
  }).returning();

  const listingsData = [
    {
      userId: seller.id,
      titleUz: "3 xonali kvartira, Chilonzor",
      titleRu: "3-комнатная квартира, Чиланзар",
      titleEn: "3-room apartment, Chilanzar",
      descriptionUz: "Chilonzor tumanida 3 xonali kvartira. Yangi ta'mirlangan, barcha qulayliklar mavjud.",
      descriptionRu: "3-комнатная квартира в Чиланзарском районе. Свежий ремонт, все удобства.",
      descriptionEn: "3-room apartment in Chilanzar district. Newly renovated, all amenities.",
      price: 85000,
      priceType: "total",
      listingType: "sale" as const,
      propertyType: "apartment" as const,
      rooms: 3,
      area: 75,
      floor: 5,
      totalFloors: 9,
      city: "Toshkent",
      district: "Chilonzor",
      address: "Buyuk Ipak Yo'li ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "2 xonali kvartira, Yunusobod",
      titleRu: "2-комнатная квартира, Юнусабад",
      titleEn: "2-room apartment, Yunusabad",
      descriptionUz: "Yunusobod tumanida zamonaviy 2 xonali kvartira. Metro yaqin.",
      descriptionRu: "Современная 2-комнатная квартира в Юнусабадском районе. Рядом метро.",
      descriptionEn: "Modern 2-room apartment in Yunusabad district. Close to metro.",
      price: 1500000,
      priceType: "month",
      listingType: "rent" as const,
      propertyType: "apartment" as const,
      rooms: 2,
      area: 55,
      floor: 3,
      totalFloors: 12,
      city: "Toshkent",
      district: "Yunusobod",
      address: "Amir Temur shoh ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "Uy, Mirzo Ulug'bek tumani",
      titleRu: "Дом, Мирзо-Улугбекский район",
      titleEn: "House, Mirzo Ulugbek district",
      descriptionUz: "Katta hovlili 5 xonali uy. Garaj va bog' bor.",
      descriptionRu: "5-комнатный дом с большим двором. Есть гараж и сад.",
      descriptionEn: "5-room house with large yard. Garage and garden available.",
      price: 180000,
      priceType: "total",
      listingType: "sale" as const,
      propertyType: "house" as const,
      rooms: 5,
      area: 200,
      floor: 2,
      totalFloors: 2,
      city: "Toshkent",
      district: "Mirzo Ulug'bek",
      address: "Bog'ishamol ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "Ofis xonasi, Shayxontohur",
      titleRu: "Офисное помещение, Шайхантахур",
      titleEn: "Office space, Shaykhantakhur",
      descriptionUz: "Markazda joylashgan zamonaviy ofis. 50 kv.m.",
      descriptionRu: "Современный офис в центре города. 50 кв.м.",
      descriptionEn: "Modern office in city center. 50 sq.m.",
      price: 2500000,
      priceType: "month",
      listingType: "rent" as const,
      propertyType: "office" as const,
      rooms: 2,
      area: 50,
      floor: 4,
      totalFloors: 8,
      city: "Toshkent",
      district: "Shayxontohur",
      address: "Mustaqillik maydoni",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "Yer uchastkasi, Sergeli",
      titleRu: "Земельный участок, Сергели",
      titleEn: "Land plot, Sergeli",
      descriptionUz: "Sergeli tumanida 6 sotixlik yer. Barcha kommunikatsiyalar bor.",
      descriptionRu: "Земельный участок 6 соток в Сергелийском районе. Все коммуникации.",
      descriptionEn: "6 sotka land plot in Sergeli district. All utilities available.",
      price: 45000,
      priceType: "total",
      listingType: "sale" as const,
      propertyType: "land" as const,
      rooms: null,
      area: 600,
      floor: null,
      totalFloors: null,
      city: "Toshkent",
      district: "Sergeli",
      address: "Yangi Sergeli ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "1 xonali kvartira, Bektemir",
      titleRu: "1-комнатная квартира, Бектимир",
      titleEn: "1-room apartment, Bektemir",
      descriptionUz: "Arzon narxda 1 xonali kvartira. Birinchi marta ijarada.",
      descriptionRu: "1-комнатная квартира по доступной цене. Впервые в аренду.",
      descriptionEn: "Affordable 1-room apartment. First time rental.",
      price: 800000,
      priceType: "month",
      listingType: "rent" as const,
      propertyType: "apartment" as const,
      rooms: 1,
      area: 35,
      floor: 2,
      totalFloors: 5,
      city: "Toshkent",
      district: "Bektemir",
      address: "Sanoat ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "4 xonali kvartira, Yakkasaroy",
      titleRu: "4-комнатная квартира, Яккасарай",
      titleEn: "4-room apartment, Yakkasaray",
      descriptionUz: "Premium kvartira. Ko'rinish ajoyib, mebel bor.",
      descriptionRu: "Премиум квартира. Прекрасный вид, с мебелью.",
      descriptionEn: "Premium apartment. Great view, furnished.",
      price: 150000,
      priceType: "total",
      listingType: "sale" as const,
      propertyType: "apartment" as const,
      rooms: 4,
      area: 120,
      floor: 10,
      totalFloors: 16,
      city: "Toshkent",
      district: "Yakkasaroy",
      address: "Amir Temur ko'chasi",
      images: [],
    },
    {
      userId: seller.id,
      titleUz: "Do'kon, Olmazor tumani",
      titleRu: "Магазин, Алмазарский район",
      titleEn: "Shop, Olmazor district",
      descriptionUz: "Band ko'chada joylashgan tijorat do'koni. Biznes uchun ideal.",
      descriptionRu: "Коммерческий магазин на оживлённой улице. Идеально для бизнеса.",
      descriptionEn: "Commercial shop on busy street. Ideal for business.",
      price: 3000000,
      priceType: "month",
      listingType: "rent" as const,
      propertyType: "commercial" as const,
      rooms: 1,
      area: 80,
      floor: 1,
      totalFloors: 3,
      city: "Toshkent",
      district: "Olmazor",
      address: "Olmazor ko'chasi",
      images: [],
    },
  ];

  await db.insert(listings).values(listingsData);

  return NextResponse.json({ success: true });
}